services:
  - type: web
    name: api-pulse-backend
    runtime: docker
    dockerfilePath: ./backend/Dockerfile
    dockerContext: .
    plan: free

    healthCheckPath: /health

    envVars:
      - key: DATABASE_URL
        sync: false

      - key: SECRET_KEY
        generateValue: true

      - key: ALGORITHM
        value: HS256

      - key: ACCESS_TOKEN_EXPIRE_MINUTES
        value: "30"

      - key: DATABASE_SSL
        value: require

      - key: CORS_ORIGINS
        value: "*"
