"""Add index to status_code

Revision ID: 3074e9a0af4f
Revises: 002_upload
Create Date: 2026-05-30 12:42:12.282417

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3074e9a0af4f'
down_revision: Union[str, None] = '002_upload'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_api_logs_status_code'), 'api_logs', ['status_code'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_api_logs_status_code'), table_name='api_logs')
    # ### end Alembic commands ###
